apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: "https://gitlab.dailin.cloud/root/camp-go-example-helm.git"
  password: glpat-grNHi1qGBxssBazFcZWY
  username: root