apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
  annotations:
    app.kubernetes.io/part-of: argocd
stringData:
  github_token: "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"
type: Opaque
