kind: Secret
apiVersion: v1
metadata:
  name: github-creds
stringData:
  # TODO 注意凭据有效性
  username: github_username
  password: github_pat
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: registry-credentials
stringData:
  # TODO 注意凭据有效性
  username: docker_username
  password: dckr_pat
type: Opaque
