apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: argo-events
  name: operate-workflow-sa
---
# Similarly you can use a ClusterRole and ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operate-workflow-role
  namespace: argo-events
rules:
  - apiGroups:
      - argoproj.io
    verbs:
      - "*"
    resources:
      - workflows
      - workflowtemplates
      - cronworkflows
      - clusterworkflowtemplates
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operate-workflow-role-binding
  namespace: argo-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operate-workflow-role
subjects:
  - kind: ServiceAccount
    name: operate-workflow-sa
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-sensor-result
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
    container:
      env:
        - name: DEBUG_LOG
          value: "true"
  dependencies:
    - name: github-event
      eventSourceName: github
      eventName: devops-camp
      filters:
        data:
          - path: "[body.commits.#.modified.@flatten,body.commits.#.added.@flatten,body.commits.#.removed.@flatten].@flatten.@flatten"
            type: string
            value:
              - "result/*"
  triggers:
    - template:
        conditions: github-event
        name: github-workflow-trigger-result
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: argo-ci-
                # namespace: argo
              spec:
                arguments:
                  parameters:
                    - name: repo
                    - name: revision
                    - name: oci-registry
                      value: "docker.io/lyzhang1999"
                    - name: oci-image
                    - name: oci-tag
                    - name: push-image
                      value: false
                    - name: microservice
                workflowTemplateRef:
                  name: argo-ci
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-event
                dataKey: body.repository.clone_url
                value: "https://github.com/devops-advanced-camp/vote.git"
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-event
                dataKey: body.after
                value: main
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-event
                dataKey: body.after
                value: main
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-event
                value: result
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-event
                value: result
