grafana:
  adminPassword: "password123"
  sidecar:
    dashboards:
      provider:
        allowUiUpdates: true
    datasources:
      defaultDatasourceEnabled: false
  service:
    type: NodePort
    nodePort: 30080

  deleteDatasources:
    - name: Prometheus
      orgId: 1

  additionalDataSources:
    - uid: prometheus
      orgId: 1
      name: Prometheus
      type: prometheus
      typeName: Prometheus
      access: proxy
      url: http://kube-prometheus-stack-prometheus:9090
      password: ""
      user: ""
      database: ""
      basicAuth: false
      isDefault: true
      jsonData:
        exemplarTraceIdDestinations:
          - datasourceUid: tempo
            name: TraceID
        httpMethod: POST
      readOnly: false
      editable: true

    - uid: alertmanager
      orgId: 1
      name: Alertmanager
      type: alertmanager
      typeName: Alertmanager
      access: proxy
      url: http://kube-prometheus-stack-alertmanager:9093

    - uid: tempo
      orgId: 1
      name: Tempo
      type: tempo
      typeName: Tempo
      access: proxy
      url: http://tempo:3100
      password: ""
      user: ""
      database: ""
      basicAuth: false
      isDefault: false
      jsonData:
        nodeGraph:
          enabled: true
        search:
          hide: false
        lokiSearch:
          datasourceUid: loki
        tracesToLogs:
          datasourceUid: loki
          filterBySpanID: false
          filterByTraceID: true
          mapTagNamesEnabled: false
          tags:
            - app
      readOnly: false
      editable: true

    - uid: loki
      orgId: 1
      name: Loki
      type: loki
      typeName: Loki
      access: proxy
      url: http://loki:3100
      password: ""
      user: ""
      database: ""
      basicAuth: false
      isDefault: false
      jsonData:
        derivedFields:
          - datasourceUid: tempo
            matcherRegex: (?:trace_id)=(\w+)
            name: TraceID
            url: $${__value.raw}
      readOnly: false
      editable: true

prometheus:
  prometheusSpec:
    enableFeatures:
      - exemplar-storage
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    externalLabels:
      cluster: k3s-hongkong-1
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
  service:
    type: NodePort
    nodePort: 30090

alertmanager:
  enabled: true
  service:
    type: NodePort
    nodePort: 30092
  alertmanagerSpec:
    alertmanagerConfigSelector:
      matchLabels:
        app: alertmanager
