grafana:
  adminPassword: "password123"
  sidecar:
    dashboards:
      provider:
        allowUiUpdates: true
  service:
    type: NodePort
    nodePort: 30080

prometheus:
  prometheusSpec:
    enableFeatures:
      - exemplar-storage
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    externalLabels:
      cluster: k3s-hongkong-1
    disableCompaction: true
    retention: 6h
    thanos:
      # enable thanos sidecar, for upload block to cos
      objectStorageConfig:
        existingSecret:
          name: thanos-objectstorage
          key: thanos.yaml
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
  thanosServiceExternal:
    enabled: true
    type: NodePort
